[workspace]

members = [
    "pcd8544", 
    "examples/rp/rp_simple"
]
resolver = "3"

[workspace.dependencies]
# embassy, all from github,
embassy-embedded-hal = { version = "0.6.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-sync = { version = "0.8.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-executor = { version = "0.10.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-time = { version = "0.5.1", git = "https://github.com/embassy-rs/embassy.git"}
embassy-rp = { version = "0.10.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-net = { version = "0.9.0", git = "https://github.com/embassy-rs/embassy.git" }
embassy-net-tuntap = { version = "0.1.1" , git = "https://github.com/embassy-rs/embassy.git"}
embassy-futures = { version = "0.1.2", git = "https://github.com/embassy-rs/embassy.git" }
cyw43 = { version = "0.7.0", git = "https://github.com/embassy-rs/embassy.git" }
cyw43-pio = { version = "0.10.0", git = "https://github.com/embassy-rs/embassy.git" }

# stuff we explicitly need for pcd8544 and examples
embedded-graphics = { version = "0.8.2"}
embedded-graphics-core = { version = "0.4.1"}
display-interface = { version = "0.5.0"}
display-interface-spi = { version = "0.5.0"}
format_no_std = { version = "1.0.2"}

# stuff we need generally somewhere (or not yet..)
defmt = { version = "1.0.1"}
defmt-rtt = {version = "1.0.0"}

cortex-m = { version = "0.7.6" }
cortex-m-rt = { version = "0.7.0"}
critical-section = { version = "1.1"}
panic-probe = { version = "1.0.0" }
heapless = {version = "0.9"}

embedded-hal-1 = { version = "1.0", package = "embedded-hal"}
embedded-hal-async = {version = "1.0"}
embedded-hal-bus = { version = "0.1" }
embedded-io-async = { version = "0.7.0" }
embedded-storage = { version = "0.3" }
static_cell = { version = "2.1" }
portable-atomic = { version = "1.5" }
log = { version = "0.4" }
rand = { version = "0.9.0" }
embedded-sdmmc = { version = "0.7.0" }
