[package]
name = "pcd8544"
version = "0.1.0"
edition = "2024"

[features]
defmt  = ["dep:defmt"]
#log = ["dep:log"]


[dependencies]

embedded-graphics = {workspace = true, features = ["defmt"]}
embedded-graphics-core = {workspace =  true, features = ["defmt"]}
display-interface = {workspace = true}

embedded-hal-1 = {workspace = true}
embedded-hal-async = {workspace = true}



defmt = { workspace = true, optional = true }
#log = { workspace = true, optional = true }

